# Generated by Django 5.0.4 on 2024-04-19 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_dishcategory_options_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishcategory',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
