# Generated by Django 5.0.4 on 2024-04-26 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(help_text='Enter phone number', max_length=20)),
                ('opening_hours', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'ordering': ['address'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('sort', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=400, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='staff/')),
                ('sort', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Staff',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='ChefSocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=20)),
                ('url', models.URLField(blank=True, null=True)),
                ('sort', models.PositiveSmallIntegerField()),
                ('chef', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='main.staff')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
                'ordering': ['sort'],
            },
        ),
    ]
